################################################################################
# ðŸŒ™ DARK THEME
################################################################################
[theme]
base="dark"
primaryColor="#00c6fb"
backgroundColor="#0d1117"
secondaryBackgroundColor="#161b22"
textColor="#e6edf3"
font="sans serif"