################################################################################
# ☀️ LIGHT THEME
################################################################################
[theme]
 base="light"
 primaryColor="#005bea"
 backgroundColor="#ffffff"
 secondaryBackgroundColor="#f0f2f6"
 textColor="#000000"
 font="sans serif"
